import 'server-only';
import { getTeamBySlug } from './teams-config';

/**
 * Confirmation email template. Sent once per Shopify order, summarizing all
 * tickets generated by that order (could be 1 ticket up to many depending
 * on what was purchased).
 *
 * Inline CSS only — Gmail strips <style> blocks. Colors mirror the brand
 * tokens used in lib/ticket-pdf.ts and the homepage so the PDF and the
 * email look like the same product.
 *
 * Returns { subject, html, text }. The text version is the plaintext
 * fallback for mail clients that don't render HTML.
 */

const NAVY = '#0a1a3a';
const GOLD = '#d4a017';
const GOLD_LIGHT = '#f5b800';
const TEXT = '#1a1a1a';
const MUTED = '#555555';
const BORDER = '#e2e2e2';
const BG = '#ffffff';

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, '') ||
  'https://theinterstatephamilyclassic.org';

export interface TicketForEmail {
  token: string;
  ticket_type: 'team_registration' | 'spectator' | 'after_party' | 'comp';
  event: 'main_event' | 'after_party';
  holder_name: string;
  team_slug: string | null;
  jersey_size: string | null;
  shorts_size: string | null;
  age_group: 'adult' | 'youth' | null;
  guardian_name: string | null;
  /** Pre-generated data URL ("data:image/png;base64,...") for inline embedding */
  qrDataUrl: string;
}

export interface OrderContext {
  buyer_first_name: string;
  shopify_order_number: string | null;
}

interface RenderedEmail {
  subject: string;
  html: string;
  text: string;
}

function ticketTypeLabel(t: TicketForEmail): string {
  if (t.ticket_type === 'team_registration') return 'TEAM REGISTRATION';
  if (t.ticket_type === 'after_party') return 'AFTER PARTY TICKET';
  if (t.ticket_type === 'comp') return 'COMPLIMENTARY';
  return t.event === 'after_party' ? 'AFTER PARTY TICKET' : 'MAIN EVENT TICKET';
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function renderTicketEmail(
  order: OrderContext,
  tickets: TicketForEmail[],
): RenderedEmail {
  const hasTeamReg = tickets.some((t) => t.ticket_type === 'team_registration');
  const firstName = order.buyer_first_name || 'Friend';
  const subject = `You're In — Interstate PHAmily Classic, August 29`;

  // ===== HTML =====
  const ticketCards = tickets
    .map((t, i) => renderTicketCardHTML(t, i + 1, tickets.length))
    .join('\n');

  const uniformBlock = hasTeamReg
    ? `
      <tr><td style="padding:16px 24px 0 24px;">
        <h3 style="font-family:Helvetica,Arial,sans-serif;font-size:13px;letter-spacing:2px;color:${GOLD};margin:0 0 8px 0;text-transform:uppercase;">Uniform Pickup</h3>
        <p style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.55;color:${TEXT};margin:0;">
          Your jersey and shorts will be available for pickup 1 hour before the event at Riverbank State Park. Valid ID required.
          Youth registrants: parent or guardian must be present.
        </p>
      </td></tr>`
    : '';

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${escapeHtml(subject)}</title>
</head>
<body style="margin:0;padding:0;background:#f2f2f2;font-family:Helvetica,Arial,sans-serif;color:${TEXT};">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f2f2f2;padding:24px 0;">
    <tr>
      <td align="center">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="background:${BG};max-width:600px;border-radius:6px;overflow:hidden;">

          <!-- Header -->
          <tr><td style="background:${NAVY};padding:32px 24px;text-align:center;">
            <div style="font-family:Helvetica,Arial,sans-serif;font-weight:700;font-size:22px;letter-spacing:3px;color:${GOLD};text-transform:uppercase;">
              Interstate PHAmily Classic
            </div>
            <div style="font-family:Helvetica,Arial,sans-serif;font-size:12px;letter-spacing:2px;color:#cbd5e1;margin-top:6px;text-transform:uppercase;">
              August 29, 2026 · Riverbank State Park
            </div>
          </td></tr>

          <!-- Greeting -->
          <tr><td style="padding:32px 24px 8px 24px;">
            <h1 style="font-family:Helvetica,Arial,sans-serif;font-size:22px;font-weight:700;color:${TEXT};margin:0 0 12px 0;">
              You're in, ${escapeHtml(firstName)}.
            </h1>
            <p style="font-family:Helvetica,Arial,sans-serif;font-size:15px;line-height:1.55;color:${TEXT};margin:0;">
              Here are your tickets for the inaugural Interstate PHAmily Classic.
              We'll see you on August 29.
            </p>
          </td></tr>

          <!-- Tickets -->
          <tr><td style="padding:8px 24px;">
            ${ticketCards}
          </td></tr>

          <!-- Event details -->
          <tr><td style="padding:16px 24px 0 24px;">
            <h3 style="font-family:Helvetica,Arial,sans-serif;font-size:13px;letter-spacing:2px;color:${GOLD};margin:0 0 8px 0;text-transform:uppercase;">Event Details</h3>
            <p style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:${TEXT};margin:0;">
              <strong>Date:</strong> Saturday, August 29, 2026<br>
              <strong>Main event:</strong> 1:00 PM – 7:00 PM<br>
              <strong>Location:</strong> Riverbank State Park, Harlem, NY<br>
              <a href="https://maps.google.com/?q=679+Riverside+Dr+New+York+NY+10031" style="color:${NAVY};text-decoration:underline;">Open in Google Maps</a>
            </p>
            <p style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.6;color:${TEXT};margin:14px 0 0 0;">
              <strong>After party:</strong> 9:00 PM onwards<br>
              <strong>Location:</strong> Most Worshipful Prince Hall Grand Lodge of New York<br>
              454 W. 155th Street, New York, NY 10032
            </p>
          </td></tr>

          ${uniformBlock}

          <!-- Important -->
          <tr><td style="padding:16px 24px 0 24px;">
            <h3 style="font-family:Helvetica,Arial,sans-serif;font-size:13px;letter-spacing:2px;color:${GOLD};margin:0 0 8px 0;text-transform:uppercase;">Important</h3>
            <p style="font-family:Helvetica,Arial,sans-serif;font-size:13px;line-height:1.55;color:${MUTED};margin:0;">
              All sales final. No refunds or exchanges. By purchasing, you've agreed to the event terms and conditions.
            </p>
          </td></tr>

          <!-- Questions -->
          <tr><td style="padding:16px 24px 24px 24px;">
            <h3 style="font-family:Helvetica,Arial,sans-serif;font-size:13px;letter-spacing:2px;color:${GOLD};margin:0 0 8px 0;text-transform:uppercase;">Questions?</h3>
            <p style="font-family:Helvetica,Arial,sans-serif;font-size:14px;line-height:1.55;color:${TEXT};margin:0;">
              Just reply to this email, or write to
              <a href="mailto:whencecameyouniversity@gmail.com" style="color:${NAVY};text-decoration:underline;">whencecameyouniversity@gmail.com</a>.
            </p>
          </td></tr>

          <!-- Footer -->
          <tr><td style="background:${NAVY};padding:24px;text-align:center;">
            <div style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${GOLD};font-weight:600;letter-spacing:2px;text-transform:uppercase;">
              PHAmily Classic
            </div>
            <div style="font-family:Helvetica,Arial,sans-serif;font-size:12px;color:#cbd5e1;margin-top:6px;">
              Hosted by Adelphic Union Lodge No. 14
            </div>
            <div style="font-family:Helvetica,Arial,sans-serif;font-size:11px;color:#cbd5e1;margin-top:10px;">
              MW Darren M. Morton, Ed.D — Grand Master
            </div>
            <div style="font-family:Helvetica,Arial,sans-serif;font-size:11px;color:rgba(255,255,255,0.4);margin-top:14px;">
              &copy; 2026 Adelphic Union Lodge No. 14, F. &amp; A.M., State of New York
            </div>
          </td></tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  // ===== Plain text =====
  const text = renderText(order, tickets);

  return { subject, html, text };
}

function renderTicketCardHTML(
  t: TicketForEmail,
  index: number,
  total: number,
): string {
  const team = t.team_slug ? getTeamBySlug(t.team_slug) : null;
  const teamLine = team ? `<strong>Team:</strong> ${escapeHtml(team.name)}<br>` : '';

  const sizeBits: string[] = [];
  if (t.jersey_size) sizeBits.push(`<strong>Jersey:</strong> ${escapeHtml(t.jersey_size)}`);
  if (t.shorts_size) sizeBits.push(`<strong>Shorts:</strong> ${escapeHtml(t.shorts_size)}`);
  const sizesLine = sizeBits.length ? `${sizeBits.join(' &middot; ')}<br>` : '';

  const guardianBlock =
    t.age_group === 'youth'
      ? `<div style="margin-top:8px;padding:8px 12px;background:#fff8e5;border-left:3px solid ${GOLD_LIGHT};font-family:Helvetica,Arial,sans-serif;font-size:13px;color:${TEXT};">
           <strong>Parent or guardian required.</strong>${
             t.guardian_name
               ? ` On file: ${escapeHtml(t.guardian_name)}.`
               : ''
           }
         </div>`
      : '';

  return `
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="border:1px solid ${BORDER};border-radius:6px;margin:12px 0;">
    <tr><td style="padding:18px 18px 0 18px;text-align:center;">
      <div style="font-family:Helvetica,Arial,sans-serif;font-size:11px;color:${MUTED};letter-spacing:2px;text-transform:uppercase;">
        Ticket ${index} of ${total}
      </div>
      <div style="font-family:Helvetica,Arial,sans-serif;font-size:12px;color:${GOLD};font-weight:700;letter-spacing:3px;margin-top:8px;text-transform:uppercase;">
        ${ticketTypeLabel(t)}
      </div>
      <div style="font-family:Helvetica,Arial,sans-serif;font-size:20px;font-weight:700;color:${TEXT};margin-top:6px;">
        ${escapeHtml(t.holder_name)}
      </div>
    </td></tr>
    <tr><td style="padding:14px 18px;text-align:center;">
      <img src="${t.qrDataUrl}" alt="Ticket QR code" width="240" height="240" style="display:block;margin:0 auto;width:240px;height:240px;">
      <div style="font-family:Helvetica,Arial,sans-serif;font-size:11px;color:${MUTED};letter-spacing:2px;text-transform:uppercase;margin-top:10px;">
        Show This At The Gate
      </div>
    </td></tr>
    ${
      teamLine || sizesLine
        ? `<tr><td style="padding:0 18px 12px 18px;text-align:center;">
             <p style="font-family:Helvetica,Arial,sans-serif;font-size:13px;line-height:1.6;color:${TEXT};margin:0;">
               ${teamLine}${sizesLine}
             </p>
           </td></tr>`
        : ''
    }
    ${
      guardianBlock
        ? `<tr><td style="padding:0 18px 12px 18px;">${guardianBlock}</td></tr>`
        : ''
    }
    <tr><td style="padding:0 18px 18px 18px;text-align:center;">
      <a href="${SITE_URL}/ticket/${encodeURIComponent(t.token)}" style="font-family:Helvetica,Arial,sans-serif;font-size:12px;color:${NAVY};text-decoration:underline;">
        View ticket online &rarr;
      </a>
    </td></tr>
  </table>`;
}

function renderText(order: OrderContext, tickets: TicketForEmail[]): string {
  const firstName = order.buyer_first_name || 'Friend';
  const hasTeamReg = tickets.some((t) => t.ticket_type === 'team_registration');

  const ticketBlocks = tickets
    .map((t, i) => {
      const lines = [
        `--- Ticket ${i + 1} of ${tickets.length} ---`,
        ticketTypeLabel(t),
        t.holder_name,
        '',
        `View ticket: ${SITE_URL}/ticket/${t.token}`,
      ];
      if (t.team_slug) {
        const team = getTeamBySlug(t.team_slug);
        if (team) lines.push(`Team: ${team.name}`);
      }
      if (t.jersey_size) lines.push(`Jersey size: ${t.jersey_size}`);
      if (t.shorts_size) lines.push(`Shorts size: ${t.shorts_size}`);
      if (t.age_group === 'youth') {
        lines.push('');
        lines.push('PARENT OR GUARDIAN REQUIRED.');
        if (t.guardian_name) lines.push(`Guardian on file: ${t.guardian_name}`);
      }
      return lines.join('\n');
    })
    .join('\n\n');

  return `INTERSTATE PHAMILY CLASSIC
August 29, 2026 · Riverbank State Park

You're in, ${firstName}.

Here are your tickets for the inaugural Interstate PHAmily Classic. We'll see
you on August 29.

${ticketBlocks}

EVENT DETAILS
Date: Saturday, August 29, 2026
Main event: 1:00 PM – 7:00 PM
Location: Riverbank State Park, Harlem, NY
Map: https://maps.google.com/?q=679+Riverside+Dr+New+York+NY+10031

After party: 9:00 PM onwards
Location: Most Worshipful Prince Hall Grand Lodge of New York
454 W. 155th Street, New York, NY 10032
${
  hasTeamReg
    ? `\nUNIFORM PICKUP\nYour jersey and shorts will be available for pickup 1 hour before the event at\nRiverbank State Park. Valid ID required. Youth registrants: parent or guardian\nmust be present.\n`
    : ''
}
IMPORTANT
All sales final. No refunds or exchanges. By purchasing, you've agreed to the
event terms and conditions.

QUESTIONS?
Reply to this email or write to whencecameyouniversity@gmail.com.

PHAmily Classic — Hosted by Adelphic Union Lodge No. 14
MW Darren M. Morton, Ed.D — Grand Master
(c) 2026 Adelphic Union Lodge No. 14, F. & A.M., State of New York
`;
}
