-- ============================================================================
-- Migration 002 — Tickets table for custom QR ticketing
-- ============================================================================
-- Run this in the Supabase SQL Editor AFTER schema.sql is already in place.
-- Idempotent: safe to re-run.
-- ============================================================================

-- ---- TICKETS ----------------------------------------------------------------
-- One row per QR-coded ticket. Generated by the Shopify webhook handler:
--   - 2 rows per team registration (the bundled spectator tickets)
--   - 1 row per spectator-ticket line-item-quantity-unit
create table if not exists public.tickets (
  id                  uuid primary key default gen_random_uuid(),

  -- Unique short code shown to the user and used for manual lookup
  -- (the QR encodes the id + a signed token; this is the human-readable handle)
  short_code          text unique not null,

  -- Source linkage
  shopify_order_id    text not null,
  shopify_order_name  text,
  registration_id     uuid references public.registrations(id) on delete set null,
                                                                  -- nullable: paid-only
                                                                  -- spectator tickets
                                                                  -- have no registration

  -- Ticket kind:
  --  'bundled-spectator' — one of the 2 free tickets included with a team registration
  --  'paid-spectator'    — a $20 ticket purchased directly
  ticket_kind         text not null check (ticket_kind in ('bundled-spectator','paid-spectator')),

  -- Buyer info (denormalized from order for fast email + check-in lookup)
  buyer_name          text not null,
  buyer_email         text not null,

  -- Lifecycle
  status              text not null default 'valid'
                      check (status in ('valid','redeemed','voided')),
  redeemed_at         timestamptz,
  redeemed_by_device  text,                          -- volunteer device identifier
  voided_at           timestamptz,
  voided_reason       text,

  created_at          timestamptz not null default now()
);

create index if not exists tickets_short_code_idx on public.tickets (short_code);
create index if not exists tickets_order_id_idx on public.tickets (shopify_order_id);
create index if not exists tickets_status_idx on public.tickets (status);
create index if not exists tickets_registration_id_idx on public.tickets (registration_id);

-- Tickets are never exposed via the public-facing roster. Lock them down via
-- RLS — only the service_role (server-side admin/webhook code) can read or
-- write.
alter table public.tickets enable row level security;

-- No SELECT policy = anon role can't read tickets at all. (Service role
-- bypasses RLS, so server code still works.)
-- We intentionally do NOT create a policy. If we ever want to expose a
-- per-ticket lookup endpoint for the buyer (e.g. "show me my ticket"), we'd
-- add a separate signed-link route on the server side rather than a broad
-- RLS policy.

-- ---- WEBHOOK EVENTS LOG -----------------------------------------------------
-- Idempotency log for incoming Shopify webhooks. Stores X-Shopify-Webhook-Id
-- so if Shopify retries a webhook we already processed, we ignore the dupe.
create table if not exists public.webhook_events (
  webhook_id          text primary key,            -- X-Shopify-Webhook-Id header
  topic               text not null,
  shopify_order_id    text,
  shopify_order_name  text,
  received_at         timestamptz not null default now(),
  processed_ok        boolean not null default false,
  error_message       text
);

create index if not exists webhook_events_order_id_idx on public.webhook_events (shopify_order_id);

alter table public.webhook_events enable row level security;
-- No public policies. Service role only.

-- ============================================================================
-- Sanity check
-- ============================================================================
-- Uncomment to verify the tables were created:
--   select count(*) as ticket_count from public.tickets;
--   select count(*) as event_count from public.webhook_events;
